package week3.day3;

import java.util.HashMap;

public class Names {
    private HashMap<String, String> students = new HashMap<>();

    public HashMap<String, String> makeStudentsMap () {
        this.students.put("권하준","https://github.com/dongyeon-0822/java-project-exercise");
        this.students.put("조성윤","https://github.com/kang-subin/Java");
        this.students.put("안예은","https://github.com/KoKwanwun/LikeLion.git");
        this.students.put("남우빈","https://github.com/lcomment/Algorithm_Solution--Java/tree/main/LikeLion");
        this.students.put("최경민","https://github.com/cmkxak/likelion-java-course");
        this.students.put("안준휘","https://github.com/rnrudejr9/CodeLion-git-test");
        this.students.put("하채민","https://github.com/Qkite/java-excercise-01/tree/main/src");
        this.students.put("허도한","https://github.com/lucyoz/java-exercise");
        this.students.put("배태훈","https://github.com/percyfrank/like-lion");
        this.students.put("정해성","https://github.com/KimGunWoo9595/Lion_Java_Pratice");
        this.students.put("하찬희","https://github.com/KimKiheon/LikeLion");
        this.students.put("박도아","https://github.com/kny3037/java-exercise");
        this.students.put("유경준","https://github.com/KimDohyoun79/remote_Lion.git");
        this.students.put("고다니엘","https://github.com/kimkimj/create-repo1");
        this.students.put("하이안","https://github.com/mingry2/intellij-git-exercise1");
        this.students.put("고유호","https://github.com/Min-ji99/intelliJ-git-exercies");
        this.students.put("전민찬","https://github.com/sangho527/Like_Lion_Java");
        this.students.put("배강","https://github.com/ReadnThink/Like_lion.git");
        this.students.put("유서이","https://github.com/yejinstar/git_exercise_push");
        this.students.put("황도빈","https://github.com/dmdwns2/java-git-init");
        this.students.put("강규진","https://github.com/Geuun/Java_Algorithm");
        this.students.put("임예린","https://github.com/O-sulloc/java-exercise-1005");
        this.students.put("양예온","https://github.com/chordpli/likelion_course");
        this.students.put("곽윤재","https://github.com/strongcookdas/java.git");
        this.students.put("한단","https://github.com/Kim-Ji-Yeong/Java-exercise");
        this.students.put("박강현","https://github.com/k0605ja/git-test");
        this.students.put("윤성민","https://github.com/pigeon2gugu/like-lion-2/tree/main/src/class_221005");
        this.students.put("박재윤","https://github.com/hj-k66/git_exercise_2");
        this.students.put("서현준","https://github.com/moomineee/JavaEx");
        this.students.put("노유주","https://github.com/sujin-park0607/java-project-exercise");
        this.students.put("전율","https://github.com/joypeb/java-project-push-test");
        this.students.put("노아린","https://github.com/pi22-a/git_practice.git");
        this.students.put("권아윤","https://github.com/JemJem70/Algolism/tree/master/src");
        this.students.put("송태서","https://github.com/BearCrying/Git_Excercise/tree/main/src");
        this.students.put("정라온","https://github.com/Bae-Ji-Won/Java-Study");
        this.students.put("서서한","https://github.com/geunnseung/java_exercise_intellij_push.git");
        this.students.put("문주호","https://github.com/JiMandy00/Java_LikeLion");
        this.students.put("오세아","JAVA-GIT-TEST/src at main · seop93/JAVA-GIT-TEST (github.com)");
        this.students.put("이호영","https://github.com/sjhlko/git-exercise-java");
        this.students.put("손윤아","https://github.com/tgseo76/javja-ex");
        this.students.put("이동우","https://github.com/seanee3670/CodeLion/tree/master/src");
        this.students.put("남혜준","https://github.com/dalddu/Intellig-git-exercise");
        this.students.put("황솔","https://github.com/hyunsik96/git-exercise-java-push");
        this.students.put("권은재","https://github.com/ccodding/git-exercise-java-push");
        this.students.put("곽준휘","https://github.com/TaylorSwiftlove/git-exercise-java");
        this.students.put("양시현","https://github.com/jinwoooooo/git-exercise-java-push");
        this.students.put("김지훈","https://github.com/simhyunbo/git-exercise-04.git");
        this.students.put("신서아","https://github.com/ahngiwon00/git-exercise-java-push");
        this.students.put("노도형","https://github.com/ahn-ji0/java_exercise");
        this.students.put("허선","https://github.com/Changbum97/like-lion-java");
        this.students.put("노지아","https://github.com/SoonMinEom/LikeALion");
        this.students.put("신아인","https://github.com/ohy1023/newtest");
        this.students.put("양시은","https://github.com/SuInWoo/LikeLion2th");
        this.students.put("노석현","손강준");
        this.students.put("백주안","https://github.com/inkyu-yoon/IntelliJ_Commit_Test");
        this.students.put("강단우","https://github.com/KaNoopy/like_lion.git");
        this.students.put("오나은","https://github.com/ondayary/java-init-project.git");
        this.students.put("오한겸","https://github.com/dohyunre702/codelion_intelliJ");
        this.students.put("백예준","https://github.com/leejoonsang/bes2");
        this.students.put("노은우","https://github.com/naegonggae/lion");
        this.students.put("손도헌","https://github.com/Soyeong4250/IntelliJPush");
        this.students.put("전진우","https://github.com/slrkajsep337/JavaStudy");
        this.students.put("안주하","https://github.com/ajin0516/java_project.git");
        this.students.put("백다은","https://github.com/yjyj1023/java-Calculator2");
        this.students.put("유민기","노휘");
        this.students.put("박채원","https://github.com/hyeonju01/likelion_repo3_test/tree/main/src/week3/day2");
        this.students.put("강다겸","https://github.com/hakjun1/intelij-git-exercise03");
        this.students.put("신여준","https://github.com/jangseoyun/Intellij-git-exercise");
        this.students.put("허은유","https://github.com/Senna97/Like-Lion");
        this.students.put("심서후","https://github.com/zinxeon/git-exercise-push");
        this.students.put("유준이","https://github.com/su0545/like-lion-java.git");
        this.students.put("전민승","https://github.com/Nickolodeon98/second-java-exercise");
        this.students.put("강예은","https://github.com/daehwan0307/JAVA_Study");
        this.students.put("허로이","https://github.com/sanghee2359?tab=repositories");
        this.students.put("유유진","https://github.com/wogus0518/LikeLion-Backend");
        this.students.put("권건하","https://github.com/heejunns/git_exercise_push.git");
        this.students.put("하도이","https://github.com/h5000n/git-java-ex211005");
        this.students.put("노도원","https://github.com/mooonju/java-exercise");
        this.students.put("문하성","https://github.com/coastby/java-project");
        this.students.put("오시후","https://github.com/Yunjaejo/new-project-push-test");
        this.students.put("이로윤","https://github.com/Combi153/BackEndSchool2");
        this.students.put("노지후","https://github.com/chlalswns200/java_push");
        this.students.put("권채이","https://github.com/S2uJeong/git-exercise-java");
        this.students.put("전담","https://github.com/gemdoq/exercise");
        this.students.put("하태율","https://github.com/surpmh/intellij-git-exercise");
        this.students.put("노다율","https://github.com/sandee-han/java-project-push-exercise");
        this.students.put("장우솔","https://github.com/JinDDung2/java-project/tree/main");
        this.students.put("황하준","https://github.com/menuhwang/LikeLion");
        return students;
    }
}
